### ISSUE TITLE
./libpostal_data: 122: [: -ge: unexpected operator

### ISSUE THREAD

**Issue by davebenvenuti** [openvenues/libpostal#305] opened 2018-01-17 19:21 UTC
On Ubuntu 16.04 on a fresh `make` I get:

`./libpostal_data: 122: [: -ge: unexpected operator`

The download still seems to work despite the syntax errors.  Perhaps `#!/bin/bash` should be defined as the interpreter at the top of the script instead of `#!/bin/sh`?

**Comment by albarrentine** [comment] 2018-01-17 19:35
Not a shell expert but I believe it needs to be the POSIX `#!/bin/sh` since not all systems have bash.

That error seems to indicate that this expression: `content_length=$(curl -I $url 2> /dev/null | awk '/^Content-Length:/ { print $2 }' | tr -d '[[:space:]]')` returned nothing, so maybe try to debug it from there.

I take it if the downloads are working then you do you have curl installed, right? Could also be an Internet issue.

**Comment by dmgk** [comment] 2018-01-17 21:01
That `Content-Length` in awk expression needs to be downcased because AWS seems to return  header names in lower case. Alternatively, awk expression can be case-insensitive:

```
content_length=$(curl -I $url 2> /dev/null | awk 'tolower($0) ~ /^content-length:/ { print $2 }' | tr -d '[[:space:]]')
```

**Comment by albarrentine** [comment] 2018-01-17 21:22
Hm, it shouldn't need to be. The data files get downloaded thousands of times every month around the world and haven't heard of any issues like that.

Here's what I see for that command. S3 version:

```
$ curl -I https://libpostal.s3.amazonaws.com/data/v1/libpostal_data.tar.gz
HTTP/1.1 200 OK
x-amz-id-2: 73DRUTSnSYWj9ZtthNf3O3UkS+QFOuPRWEBdziUDjkFLO3vEk3S7NYJmgKX/YMEIdnrdKyhVjZg=
x-amz-request-id: 5354CB00F3516303
Date: Wed, 17 Jan 2018 21:12:17 GMT
Last-Modified: Tue, 16 Jan 2018 09:30:42 GMT
ETag: "d465d2216710b5d89b97d04b2b0c32a8-2"
Accept-Ranges: bytes
Content-Type: application/x-tar
Content-Length: 10321022
Server: AmazonS3
```

CloudFront version:

```
$ curl -I https://d1p366rbd94x8u.cloudfront.net/data/v1/libpostal_data.tar.gz
HTTP/1.1 200 OK
Content-Type: application/x-tar
Content-Length: 10321022
Connection: keep-alive
Date: Wed, 17 Jan 2018 13:39:00 GMT
Last-Modified: Tue, 16 Jan 2018 09:30:42 GMT
ETag: "d465d2216710b5d89b97d04b2b0c32a8-2"
Accept-Ranges: bytes
Server: AmazonS3
X-Cache: RefreshHit from cloudfront
Via: 1.1 5f5ca5852c74982e7459707a6c9e215a.cloudfront.net (CloudFront)
X-Amz-Cf-Id: MomIeDeaJQ0zgdQnBvTzj6iAW0D2brWdebaaYl3lxtb4ejgWu8sYPA==
```

Are you getting something different?

Note: we're also moving the release downloads from AWS to Github pretty soon.

**Comment by dmgk** [comment] 2018-01-17 22:15
I cannot reproduce this now (perhaps it was a transient issue with some midway proxy) but I had to make this change in the libpostal FreeBSD port that I maintain.

Anyway, HTTP headers are not case sensitive and there's no guarantee that Content-Type will always be returned as `Content-Type`. So I think it would make sense to update that awk expression to do a more robust case-insensitive comparison.

**Comment by albarrentine** [comment] 2018-01-17 22:36
Added in 95e483e3cad1ca7795159c88187e4f1590bc04b1, that should hopefully fix the issue.

**Comment by albarrentine** [comment] 2018-01-20 00:21
Think this is solved, closing if there are no objections.

**Closed by albarrentine** 2018-01-20 00:21 UTC
