### ISSUE TITLE
Request kills expand_address

### ISSUE THREAD

**Issue by russellbluck** [openvenues/libpostal#193] opened 2017-04-28 12:35 UTC
I have an address that is killing the entire parser - which is being run as the only process on a fairly beefy server.  It takes 100% CPU before eventually dying.

The address is

HNO 1 WANDERWEG ENGERWITZ DORF 4209 AUSTRIA AT

What is interesting is that if I change WANDERWEG to WANDERSTREET, it parses without issue.  Obviously that isn't a viable solution as I'm changing the data.

Any ideas?  It would be nice if the tool could also have a processing limit whereby if it hasn't parsed the address within a certain amount of time, then it returns nothing.

FYI the code I'm using is below (filters are both empty)

public Address parse(String raw, Prefilter[] prefilters, Postfilter[] postfilters) {

    	AddressController.LOGGER.debug("Before address Parser");
        com.mapzen.jpostal.AddressParser a = com.mapzen.jpostal.AddressParser.getInstance();
        AddressController.LOGGER.debug("After address Parser"); 
        com.mapzen.jpostal.AddressExpander e = com.mapzen.jpostal.AddressExpander.getInstance();
        AddressController.LOGGER.debug("After address Expander");
        
        for (Integer i = 0; i < prefilters.length; i++) {
            raw = prefilters[i].filter(raw);
        }
        Address addr = new Address();
        addr.setRaw(raw);
        
        ParsedComponent[] components = null;
        String countryIsoCode = getCountryCode(raw); //Get a 2 character ISO country code
	    if (countryIsoCode != null) {
	        ParserOptions.Builder builder =  new ParserOptions.Builder();
	        builder.country(countryIsoCode);
	        ParserOptions options = new ParserOptions(builder);
	
	        components = a.parseAddressWithOptions(raw, options);
        }
        else {
        	components = a.parseAddress(raw);
        }
        String[] expansions = e.expandAddress(raw);
        for (Integer i = 0; i < expansions.length; i ++) {
            addr.set("expansion", expansions[i]);
        }

        for (ParsedComponent c : components) {
            String label = c.getLabel();
            String value = c.getValue();
            addr.set(label, value);
        }

        for (Integer i = 0; i < postfilters.length; i++) {
            addr = postfilters[i].filter(addr);
        }
        return addr;
    }

**Comment by mkaranta** [comment] 2017-04-28 13:35
It looks like you are using java & jni here. It seems to work fine (and instantaneously) in the C code below. 

`> HNO 1 WANDERWEG ENGERWITZ DORF 4209 AUSTRIA AT

Result:

{
  "road": "hno 1 wanderweg engerwitz dorf",
  "postcode": "4209",
  "country": "austria at"
}

> HNO 1 WANDERSTREET ENGERWITZ DORF 4209 AUSTRIA AT

Result:

{
  "house": "hno 1 wanderstreet engerwitz",
  "road": "dorf",
  "postcode": "4209",
  "country": "austria at"
}`

What's the last line of code executed in your sample?

**Comment by russellbluck** [comment] 2017-04-28 13:42
It dies at the line

components = a.parseAddress(raw);

We have a java client/server architecture but are really just using the jpostal library to interact with the C code

**Comment by mkaranta** [comment] 2017-04-28 14:39
We do the same thing with supervisorctl monitoring the process and restarting the server if it dies. That only happened once due to an OOM error that we could never reproduce. The address logs from the time were unfortunately overwritten by the time we noticed.

So I'm quite interested in solving this little mystery.

**Comment by russellbluck** [comment] 2017-04-28 14:44
I removed this line and it appears happier now...

com.mapzen.jpostal.AddressExpander e = com.mapzen.jpostal.AddressExpander.getInstance();

Looks like the expansions caused the issue.  Don't know if that will help you.

**Comment by mkaranta** [comment] 2017-04-28 15:02
Never used the expander in the Java code. Do get an instance of it though. 

Looks like you found the issue though. The C code runs forever:
```~/libpostal$ ./src/libpostal "HNO 1 WANDERWEG ENGERWITZ DORF 4209 AUSTRIA AT"```

**Comment by thatdatabaseguy** [comment] 2017-04-28 15:33
@russellbluck @mkaranta ok, that was indeed a bug on the C side, tracked down in valgrind. It can happen in the case where something that could be a separable suffix ("Foowanderweg" could be expanded to "foo wanderweg" in German) is the entire token ("wanderweg" on its own). Pull latest to pick up this commit: https://github.com/openvenues/libpostal/commit/6ea22732630da11948801dc60b458dcc66fd7af3 and that should fix it.

**Comment by thatdatabaseguy** [comment] 2017-04-28 16:24
@russellbluck, a processing time limit wouldn't really make sense for this case. The only reason the C calls would take more than a few microseconds is if there's excessively long input or a memory bug like the above. This is the only instance of a memory bug I've encountered in a long time, and libpostal gets tested on over a million addresses from a production geocoder to check for memory issues. That data set contains bad input, long input, multi-script input, etc. and has been useful in debugging libpostal's expand_address calls, although it only contains about 10k German addresses and there were no instances of the word "Wanderweg", so will try to use a more comprehensive test corpus going forward.

**Comment by thatdatabaseguy** [comment] 2017-04-28 19:10
Closing if there are no objections

**Closed by thatdatabaseguy** 2017-04-28 19:10 UTC
